UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " BV", " BLVD");
#UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " AV", " AVE");
UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " CR", " CIR");
UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " WY", " WAY");
UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " TL", " TRL");
#UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " HW", " HWY");
UPDATE parcel SET SITE_ADDR = REPLACE(SITE_ADDR, " PW", " PKWY");
